wedsite/models.py
from . import db
from werkzeug.security import generate_password_hash, check_password_hash


class Product(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    product_name = db.Column(db.String(100), nullable=False)
    current_price = db.Column(db.Float, nullable=False)
    previous_price = db.Column(db.Float, nullable=False)
    product_picture = db.Column(db.String(1000), nullable=False)
    product_tag = db.Column(db.String(50), nullable=False)


    def __str__(self):
        return '<Product %r>' % self.product_name
    

class BestSeller(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    product_name = db.Column(db.String(100), nullable=False)
    current_price = db.Column(db.Float, nullable=False)
    previous_price = db.Column(db.Float, nullable=False)
    product_picture = db.Column(db.String(1000), nullable=False)
    product_tag = db.Column(db.String(50), nullable=False)


    def __str__(self):
        return '<BestSeller %r>' % self.product_name
    
class BestOffers(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    product_name = db.Column(db.String(100), nullable=False)
    current_price = db.Column(db.Float, nullable=False)
    previous_price = db.Column(db.Float, nullable=False)
    product_picture = db.Column(db.String(1000), nullable=False)
    product_tag = db.Column(db.String(50), nullable=False)


    def __str__(self):
        return '<Product %r>' % self.product_name
    

class Instagram(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    product_picture = db.Column(db.String(1000), nullable=False)



    def __str__(self):
        return '<Product %r>' % self.product_picture
    

class ProductPage(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    product_name = db.Column(db.String(100), nullable=False)
    current_price = db.Column(db.Float, nullable=False)
    previous_price = db.Column(db.Float, nullable=False)
    product_picture = db.Column(db.String(1000), nullable=False)
    product_tag = db.Column(db.String(50), nullable=False)


    def __str__(self):
        return '<Product %r>' % self.product_name
    

wedsite/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField, FloatField, PasswordField, EmailField, BooleanField, SubmitField, SelectField
from wtforms.validators import DataRequired, length, NumberRange
from flask_wtf.file import FileField, FileRequired





class ShopItemsForm(FlaskForm):
    choices = [('all', 'All Products'), ('kids', 'Kids'), ('boys', 'Boys'), ('girls', 'Girls'), ('men', 'Men'), ('women', 'Woman')]
    product_name = StringField('Name of Product', validators=[DataRequired()])
    current_price = FloatField('Current Price', validators=[DataRequired()])
    previous_price = FloatField('Previous Price', validators=[DataRequired()])
    product_picture = FileField('Product Picture', validators=[DataRequired()])
    product_tag = SelectField('Product Filter', choices=choices, default='all')

    add_product = SubmitField('Add Product')
    update_product = SubmitField('Update')

class InstaForm(FlaskForm):
    product_picture = FileField('Product Picture', validators=[DataRequired()])
    
    add_product = SubmitField('Add Product')

wedsite/__init__.py
from flask import Flask, render_template
from flask_sqlalchemy import SQLAlchemy


db = SQLAlchemy()
DB_NAME = 'database.sqlite3'


def create_database():
    db.create_all()
    print('Database Created')

# def delete_database():
#     db.drop_all()
#     print('DataBase deleted')


def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'hbnwdvbn ajnbsjn ahe'
    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}'

    db.init_app(app)


    from .views import views
    from .auth import auth
    from .admin import admin
    from .models import Product, BestSeller, BestOffers, Instagram, ProductPage

    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(auth, url_prefix='/')
    app.register_blueprint(admin, url_prefix='/')

    with app.app_context():
        create_database()

    # with app.app_context():
    #     delete_database()

    return app

wedsite/auth.py
from flask import Blueprint, render_template, session, redirect, request
# from .forms import LoginForm, SignUpForm, PasswordChangeForm
# from .models import Customer
# from . import db




auth = Blueprint('auth', __name__)


SINGLE_USER = {'username': 'test', 'password': 'test'}

def login_required(view_func):
    def wrapper(*args, **kwargs):
        if 'logged_in' in session:
            return view_func(*args, **kwargs)
        else:
            return redirect('/login')
    return wrapper

@auth.route("/login", methods=["GET", "POST"])
def login():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']

        if username == SINGLE_USER['username'] and password == SINGLE_USER['password']:
            session['logged_in'] = True
            session['username'] = username
            return redirect('/dashboard')
        else:
            return render_template('login.html', error='Invalid credentials')

    return render_template("login.html")

@auth.route('/logout')
@login_required
def logout():
    session.pop('logged_in', None)
    session.pop('username', None)
    return redirect('/')

wedsite/views.py
from flask import Blueprint, render_template, flash, redirect, request, jsonify
from .models import Product,BestOffers,Instagram, BestSeller, ProductPage
from . import db


views = Blueprint('views', __name__)

API_PUBLISHABLE_KEY = 'YOUR_PUBLISHABLE_KEY'

API_TOKEN = 'YOUR_API_TOKEN'


@views.route('/')
def index():
    items = Product.query.all()
    items_bestSeller = BestSeller.query.all()
    items_bestOffer = BestOffers.query.all()
    items_insta = Instagram.query.all()
    items_product = ProductPage.query.all()
    return render_template("index.html", items = items, 
                           items_bestSeller=items_bestSeller, 
                           items_bestOffer=items_bestOffer, 
                           items_insta = items_insta, 
                           items_product=items_product)


@views.route("/about")
def about():
    return render_template("about.html")

@views.route("/product", methods=['GET', 'POST'])
def product():
    items = ProductPage.query.all()
    return render_template("product.html", items = items)


@views.route("/contact")
def contact():
    return render_template("contact.html")


@views.route("/dashboard")
def dashboard():
    return render_template("dashboard.html")

wedsite/templates/header.html
<header class="header-area header-style-4 header-height-2">
    <div class="header-top header-top-ptb-1 d-none d-lg-block" style="background-color:#2f515a;">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-xl-4 col-lg-4">
                    <div class="header-info">
                        <ul>
                            <!-- <li style="color:white;"><i class="fi-rs-smartphone"></i> <a href="#" style="color:white;">(+91)-8189922949</a></li> -->
                            <li style="color:white;"><i class="fi-rs-marker"></i><a  href="https://maps.app.goo.gl/mAfWA1dnAhPTsMmQ9" style="color:white;">Our Location : Khaderpet, Tirupur</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-xl-5 col-lg-4">
                    <div class="text-center">
                        <div id="news-flash" class="d-inline-block"  style="color:white;font-size:12px;"> 
                            <ul>
                                <li>Get great Products up to 60% off </li>
                                <li>Supper Value Deals - Save more with coupons</li>
                                <li>Use Promo Code ATX2024 for 10% OFF </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-xl-3 col-lg-4">
                    <div class="header-info header-info-right">
                        <ul>
                            <!-- <li>
                                <a class="language-dropdown-active" href="#"> <i class="fi-rs-world"></i> English <i class="fi-rs-angle-small-down"></i></a>
                                <ul class="language-dropdown">
                                    <li><a href="#"><img src="assets/imgs/theme/flag-fr.png" alt="">Français</a></li>
                                    <li><a href="#"><img src="assets/imgs/theme/flag-dt.png" alt="">Deutsch</a></li>
                                    <li><a href="#"><img src="assets/imgs/theme/flag-ru.png" alt="">Pусский</a></li>
                                </ul>
                            </li> -->
                            <li><i class="fa-brands fa-facebook fa-2xl" style="color: #ffffff;"></i></li>
                            <li><i class="fa-brands fa-whatsapp fa-2xl" style="color: #ffffff;"></i></li>
                            <li><i class="fa-brands fa-instagram fa-2xl" style="color: #ffffff;"></i></li>
                            <li><i class="fa-brands fa-youtube fa-2xl" style="color: #ffffff;"></i></li>
                        </ul>

                      
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    <div class="header-bottom header-bottom-bg-color sticky-bar">
        <div class="container">
            <div class="header-wrap header-space-between position-relative">
              
                <div class="header-nav d-none d-lg-flex">
                    <div class="main-categori-wrap d-none d-lg-block">
                        <div class="logo logo-width-1">
                            <a href="{{ url_for('views.index') }}"><img src="static/imgs/theme/logo.png" alt="logo" style="height:66px; width:250px; margin-top:12px;"></a>
                        </div>
                      
                    </div>

                   
                   
                    <div class="main-menu main-menu-padding-1 main-menu-lh-2 d-none d-lg-block" >
                        <nav>
                            <ul>
                                <li><a  href="{{ url_for('views.index') }}">Home</a>
                                   
                                </li>
                                <li>
                                    <a href="{{ url_for('views.about') }}">About</a>
                                </li>
                               
                                <li ><a href="{{ url_for('views.product') }}">Products </a>
                                   
                                </li>
                              
                               
                                <li>
                                    <a href="{{ url_for('views.contact') }}">Contact</a>
                                </li>

                  
                                <li>
                                    <a href="{{ url_for('auth.login') }}">Login</a>
                                </li>
          
                                <!-- <li>
                                    <a href="{{ url_for('views.index') }}">Logout</a>
                                </li> -->
               

                            <!-- <li class="nav-item dropdown">
                                    <ul class="dropdown-menu">
                                     
                                        
                                        <li><a class="dropdown-item" href="{{ url_for('auth.login') }}">Logout</a></li>
                                    </ul>
                                    </li> -->

                              
                            </ul>
                        </nav>
                    </div>
                </div>
           

                <div class="hotline d-none d-lg-block" >
                    <p><i class="fi-rs-headset"></i><span>For Enquiry</span>(+91)-8189922949</p>
                </div>
                
            
                <div class="header-action-right d-block d-lg-none">
                    <div class="header-action-2">
                        <div class="header-action-icon-2">
                         
                        </div>
                        <div class="header-action-icon-2">
                          
                        
                        </div>
                        <div class="header-action-icon-2 d-block d-lg-none">
                            <div class="burger-icon burger-icon-white">
                                <span class="burger-icon-top"></span>
                                <span class="burger-icon-mid"></span>
                                <span class="burger-icon-bottom"></span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>
<div class="mobile-header-active mobile-header-wrapper-style">
    <div class="mobile-header-wrapper-inner">
        <div class="mobile-header-top">
            <div class="mobile-header-logo">
                <a href="index.php"><img src="static/imgs/theme/logo.png" alt="logo"></a>
            </div>
          
        </div>
        <div class="mobile-header-content-area">
          
            <div class="mobile-menu-wrap mobile-header-border">
               
                <!-- mobile menu start -->
                <nav>
                    <ul class="mobile-menu">
                        <li class="menu-item-has-children"><span class="menu-expand"></span><a href="{{ url_for('views.index') }}">index</a>
                            
                        </li>

                        <li class="menu-item-has-children"><span class="menu-expand"></span><a href="{{ url_for('views.about') }}">About</a>
                         
                        </li>
                      
                        <li class="menu-item-has-children"><span class="menu-expand"></span><a href="{{ url_for('views.product') }}">Products</a>
                          
                        </li>
                      
                        <li class="menu-item-has-children"><span class="menu-expand"></span><a href="{{ url_for('views.contact') }}">Contact</a>
                           
                        </li>

                        <li class="menu-item-has-children"><span class="menu-expand"></span><a href="{{ url_for('auth.login') }}">Login</a>
                           
                        </li>
                     
                    </ul>
                </nav>
                <!-- mobile menu end -->
            </div>
            
        
        </div>
    </div>
</div>
</header>

wedsite/templates/login.html
{% extends 'index.html' %}

{% block content %}

<main class="main">
  <div class="page-header breadcrumb-wrap">
      <div class="container">
          <div class="breadcrumb">
              <a href="index.html" rel="nofollow">Home</a>
              <span></span> Pages
              <span></span> Login / Register
          </div>
      </div>
  </div>
  <section class="pt-150 pb-150">
      <div class="container">
          <div class="row">
              <div class="col-lg-10 m-auto">
                  <div class="row">
                      <div class="col-lg-5">
                          <div class="login_wrap widget-taber-content p-30 background-white border-radius-10 mb-md-5 mb-lg-0 mb-sm-5">
                              <div class="padding_eight_all bg-white">
                                  <div class="heading_s1">
                                      <h3 class="mb-30">Login</h3>
                                  </div>
                                  <form action="/login" method="POST">
                                      <div class="form-group">
                                          <input type="text" required="" name="username" placeholder="User Name">
                                      </div>
                                      <div class="form-group">
                                          <input required="" type="password" name="password" placeholder="Password">
                                      </div>
                                      <div class="login_footer form-group">
                                          <div class="chek-form">
                                              <div class="custome-checkbox">
                                                  <input class="form-check-input" type="checkbox" name="checkbox" id="exampleCheckbox1" value="">
                                                  <label class="form-check-label" for="exampleCheckbox1"><span>Remember me</span></label>
                                              </div>
                                          </div>
                                          <a class="text-muted" href="#">Forgot password?</a>
                                      </div>
                                      <div class="form-group">
                                          <button type="submit" class="btn btn-fill-out btn-block hover-up" name="login">Log in</button>
                                      </div>
                                  </form>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
  </section>
</main>
  
     

    {% endblock %}

wedsite/templates/update_get_bestoffers_item.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="apple-touch-icon" sizes="76x76" href="{{ url_for('static', filename='img/apple-icon.png') }}">
  <link rel="icon" type="image/png" href="{{ url_for('static', filename='img/favicon.png') }}">
  <title>
    Arun Textiles Dashboard 
  </title>
  <!--     Fonts and icons     -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet" />
  <!-- Nucleo Icons -->
  <link href="{{ url_for('static', filename='css/nucleo-icons.css') }}" rel="stylesheet" />
  <link href="{{ url_for('static', filename='css/nucleo-svg.css') }}" rel="stylesheet" />
  <!-- Font Awesome Icons -->
  <script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>
  <link href="{{ url_for('static', filename='css/nucleo-svg.css') }}" rel="stylesheet" />
  <!-- CSS Files -->
  <link id="pagestyle" href="{{ url_for('static', filename='css/argon-dashboard.css') }}" rel="stylesheet" />
</head>

<body class="g-sidenav-show   bg-gray-100">
  <div class="min-height-300  position-absolute w-100" style="background-color:#2f515a;"></div>
  <aside class="sidenav bg-white navbar navbar-vertical navbar-expand-xs border-0 border-radius-xl my-3 fixed-start ms-4 " id="sidenav-main">
    <div class="sidenav-header">
      <i class="fas fa-times p-3 cursor-pointer text-secondary opacity-5 position-absolute end-0 top-0 d-none d-xl-none" aria-hidden="true" id="iconSidenav"></i>
      <a class="navbar-brand m-0" href="{{ url_for('views.index') }} " target="_blank" style="height:160px; width:350px; margin-top:12px;">
        <img src="{{ url_for('static', filename='imgs/theme/logo-2.svg') }}" class="navbar-brand-img" alt="main_logo"></a>
          <span class="ms-1 font-weight-bold text-white"></span>
        </a>
    </div>
    <hr class="horizontal dark mt-0">
    <div class="collapse navbar-collapse  w-auto " id="sidenav-collapse-main">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" href="{{ url_for('views.dashboard') }} ">
            <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
              <i class="ni ni-tv-2 text-primary text-sm opacity-10"></i>
            </div>
            <span class="nav-link-text ms-1">Dashboard</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{{ url_for('admin.dash_product') }}">
            <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
              <i class="ni ni-calendar-grid-58 text-warning text-sm opacity-10"></i>
            </div>
            <span class="nav-link-text ms-1">Products</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{{ url_for('admin.shop_items') }}">
            <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
              <i class="ni ni-single-copy-04 text-warning text-sm opacity-10"></i>
            </div>
            <span class="nav-link-text ms-1">New Arrivales</span>
          </a>
        </li>
        
        <li class="nav-item">
          <a class="nav-link active" href="{{ url_for('admin.dash_bestseller') }}">
            <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
              <i class="ni ni-credit-card text-success text-sm opacity-10"></i>
            </div>
            <span class="nav-link-text ms-1">Best Sellers</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{{ url_for('admin.dash_bestoffers') }}">
            <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
              <i class="ni ni-app text-info text-sm opacity-10"></i>
            </div>
            <span class="nav-link-text ms-1">Best Offers</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{{ url_for('admin.dash_insta') }}">
            <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
              <i class="ni ni-world-2 text-danger text-sm opacity-10"></i>
            </div>
            <span class="nav-link-text ms-1">Instagram</span>
          </a>
        </li>
        
        
   
      </ul>
    </div>
  </aside>


{% block content %}

<main class="main-content position-relative border-radius-lg ">
    <!-- Navbar -->
    <nav class="navbar navbar-main navbar-expand-lg px-0 mx-4 shadow-none border-radius-xl " id="navbarBlur" data-scroll="false">
      <div class="container-fluid py-1 px-3">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb bg-transparent mb-0 pb-0 pt-1 px-0 me-sm-6 me-5">
            <li class="breadcrumb-item text-sm"><a class="opacity-5 text-white" href="javascript:;">Dashboard</a></li>
            <li class="breadcrumb-item text-sm text-white active" aria-current="page">Best Offer</li>
          </ol>
          <h6 class="font-weight-bolder text-white mb-0">Best Offer</h6>
        </nav>
       
    </nav>
    <!-- End Navbar -->

    <!-- <hr> -->

    <!-- Table to display existing products -->
    

   
    <div class="container">

        <div class="row">
        
            <div class="col-md-12">
    
                <div class="card">
    
                    <div class="row">
                        <div class="col-md-10" style="padding:16px;">
                            <h4 style="margin-left:10px">Best Offers</h4> 
                        </div>
    
                    </div>
    
                    <div class="card-body" id="products-table">
    
                        <table class="table table-bordered table-striped">
    
                            <thead>
                                <tr>
                                    <th>Product Name</th>
                                    <th>Previous Price</th>
                                    <th>Current Price</th>
                                    <th>Product Picture</th>
                                    <th>Product Tag</th>
                                    <th>Add</th>
                                </tr>
                            </thead>
    
                            <tbody>
                                <tr>
                                    <form action="" method="post" enctype="multipart/form-data">
                                      <td><input type="text" name="product_name" class="form-control" value="{{item_to_update.product_name}}"></td>
                                      <td><input type="text" name="previous_price" class="form-control" value="{{item_to_update.previous_price}}"></td>
                                      <td><input type="text" name="current_price" class="form-control" value="{{ item_to_update.current_price }}"></td>
                                      <td><input type="text" name="product_picture" class="form-control" value="{{ item_to_update.product_picture }}"></td>
                                      <td>
                                        <select name="product_tag" class="form-select">
                                          <option value="all"
                                          {% if 'all' in item_to_update.product_tag %}
                                          selected
                                          {% endif %}
                                          >All</option>
                                          <option value="men"
                                          {% if 'men' in item_to_update.product_tag %}
                                          selected
                                          {% endif %}
                                          >Men</option>
                                          <option value="women"
                                          {% if 'Woman' in item_to_update.product_tag %}
                                          selected
                                          {% endif %}
                                          >Woman</option>
                                          <option value="boys"
                                          {% if 'boys' in item_to_update.product_tag %}
                                          selected
                                          {% endif %}
                                          >Boys</option>
                                          <option value="girls"
                                          {% if 'girls' in item_to_update.product_tag %}
                                          selected
                                          {% endif %}
                                          >Girls</option>
                                          <option value="kids"
                                          {% if 'kids' in item_to_update.product_tag %}
                                          selected
                                          {% endif %}
                                          >kids</option>
                                        </select>
                                      </td>
                                      <td>
                                        <input type="submit" name="submit" value="submit" class="btn btn-success"> 
                                      </td>
                                    </form>
                                </tr>
                            </tbody>
    
                        </table>
    
                    </div>
                </div>
    
            </div>
           
        </div>
        

        

  
  <!--   Core JS Files   -->
  <script src="{{ url_for('static', filename='js/core/popper.min.js') }}"></script>
  <script src="{{ url_for('static', filename='js/core/bootstrap.min.js') }}"></script>
  <script src="{{ url_for('static', filename='js/plugins/perfect-scrollbar.min.js') }}"></script>
  <script src="{{ url_for('static', filename='js/plugins/smooth-scrollbar.min.js') }}"></script>
  <script src="{{ url_for('static', filename='js/plugins/chartjs.min.js') }}"></script>
  <script>
    var ctx1 = document.getElementById("chart-line").getContext("2d");

    var gradientStroke1 = ctx1.createLinearGradient(0, 230, 0, 50);

    gradientStroke1.addColorStop(1, 'rgba(94, 114, 228, 0.2)');
    gradientStroke1.addColorStop(0.2, 'rgba(94, 114, 228, 0.0)');
    gradientStroke1.addColorStop(0, 'rgba(94, 114, 228, 0)');
    new Chart(ctx1, {
      type: "line",
      data: {
        labels: ["Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
        datasets: [{
          label: "Mobile apps",
          tension: 0.4,
          borderWidth: 0,
          pointRadius: 0,
          borderColor: "#5e72e4",
          backgroundColor: gradientStroke1,
          borderWidth: 3,
          fill: true,
          data: [50, 40, 300, 220, 500, 250, 400, 230, 500],
          maxBarThickness: 6

        }],
      },
      options: {
        responsive: true,
        maintainAspectRatio: false,
        plugins: {
          legend: {
            display: false,
          }
        },
        interaction: {
          intersect: false,
          mode: 'index',
        },
        scales: {
          y: {
            grid: {
              drawBorder: false,
              display: true,
              drawOnChartArea: true,
              drawTicks: false,
              borderDash: [5, 5]
            },
            ticks: {
              display: true,
              padding: 10,
              color: '#fbfbfb',
              font: {
                size: 11,
                family: "Open Sans",
                style: 'normal',
                lineHeight: 2
              },
            }
          },
          x: {
            grid: {
              drawBorder: false,
              display: false,
              drawOnChartArea: false,
              drawTicks: false,
              borderDash: [5, 5]
            },
            ticks: {
              display: true,
              color: '#ccc',
              padding: 20,
              font: {
                size: 11,
                family: "Open Sans",
                style: 'normal',
                lineHeight: 2
              },
            }
          },
        },
      },
    });
  </script>
  <script>
    var win = navigator.platform.indexOf('Win') > -1;
    if (win && document.querySelector('#sidenav-scrollbar')) {
      var options = {
        damping: '0.5'
      }
      Scrollbar.init(document.querySelector('#sidenav-scrollbar'), options);
    }
  </script>
  <!-- Github buttons -->
  <script async defer src="https://buttons.github.io/buttons.js"></script>
  <!-- Control Center for Soft Dashboard: parallax effects, scripts for the example pages etc -->
  <script src="{{ url_for('static', filename='js/argon-dashboard.min.js') }}"></script>
</body>





{% endblock %}